[package]
name = "joinster"
version = "0.1.0"
edition = "2021"

[dependencies]
num_cpus = "1.16.0"
pollster = "0.3.0"

[dev-dependencies]
rayon = "1.10.0"
tokio = { version = "1.38.0", features = ["rt", "macros", "rt-multi-thread"] }
